# Generated by Django 3.1.4 on 2021-01-15 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
                ('address2', models.CharField(blank=True, max_length=225, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_qty', models.DecimalField(decimal_places=0, max_digits=2)),
                ('amenities', models.BooleanField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
                ('create_to', models.DateTimeField(auto_now_add=True)),
                ('update_to', models.DateTimeField(auto_now=True)),
                ('supplier', models.ManyToManyField(blank=True, null=True, related_name='suppliers', to='settings.Supplier')),
                ('type_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.classification')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ['create_to'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.DecimalField(decimal_places=0, max_digits=2)),
                ('meter_qty', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('flat', models.CharField(blank=True, max_length=20, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('init_date', models.DateField(blank=True, null=True)),
                ('renovation_date', models.DateField(blank=True, null=True)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('state', models.BooleanField(default=True)),
                ('create_to', models.DateTimeField(auto_now_add=True)),
                ('update_to', models.DateTimeField(auto_now=True)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.building')),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.classification')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['create_to'],
            },
        ),
        migrations.CreateModel(
            name='CommonExpenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('state', models.BooleanField(default=True)),
                ('create_to', models.DateTimeField(auto_now_add=True)),
                ('update_to', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.unit')),
            ],
            options={
                'verbose_name_plural': 'Common Expenses',
            },
        ),
    ]
