# Generated by Django 3.1.4 on 2021-01-16 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_auto_20210115_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonexpenses',
            name='apartment',
        ),
        migrations.AddField(
            model_name='commonexpenses',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonexpenses',
            name='building',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='building.building'),
            preserve_default=False,
        ),
    ]
