# Generated by Django 3.1.4 on 2021-01-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_auto_20210116_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='rent_price',
            field=models.IntegerField(default=0),
        ),
    ]
