# Generated by Django 3.1.4 on 2021-01-16 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_auto_20210116_0400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonexpenses',
            options={'ordering': ['payment_date'], 'verbose_name_plural': 'Common Expenses'},
        ),
        migrations.RenameField(
            model_name='commonexpenses',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.CreateModel(
            name='CommonExpensesLines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('concept', models.CharField(max_length=225)),
                ('state', models.BooleanField(default=True)),
                ('create_to', models.DateTimeField(auto_now_add=True)),
                ('update_to', models.DateTimeField(auto_now=True)),
                ('common_expenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.commonexpenses')),
            ],
            options={
                'verbose_name_plural': 'Common Expenses',
                'ordering': ['create_to'],
            },
        ),
    ]
