# Generated by Django 3.1.4 on 2021-01-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_auto_20210116_0532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonexpenseslines',
            options={'ordering': ['create_to'], 'verbose_name_plural': 'Common Expenses Lines'},
        ),
    ]
