# Generated by Django 3.1.4 on 2021-01-15 04:36

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
                ('superuser', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='images/', verbose_name='Image')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'CUSTOMER'), (2, 'EMPLOYEE')])),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='settings.company')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
