# Generated by Django 3.1.4 on 2021-01-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210115_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='company',
        ),
    ]
